#!/bin/sh

### BEGIN INIT INFO
# Provides:          amigobooth
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the amigobooth web server
# Description:       starts amigobooth
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/home/pi/amigo
NAME=amigobooth
DESC=amigobooth
PID=/tmp/amigobooth.pid
USERNAME=pi

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
    echo -n "Starting $DESC: "
    start-stop-daemon --start --quiet --chuid $USERNAME --background --pidfile $PID --exec $DAEMON || true
    echo "$NAME."
    ;;

  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon --stop --quiet --chuid $USERNAME --pidfile $PID --exec $DAEMON || true
    echo "$NAME."
    ;;

  restart)
    echo -n "Restarting $DESC: "
    start-stop-daemon --stop --quiet --chuid $USERNAME --pidfile $PID --exec $DAEMON || true
    sleep 1
    start-stop-daemon --start --quiet --chuid $USERNAME --background --pidfile $PID --exec $DAEMON || true
    echo "$NAME."
    ;;

  *)
    echo "Usage: $NAME {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
